security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                            provider: fos_userbundle
                            # csrf token options
                            csrf_parameter:       _csrf_token
                            csrf_token_id:        authenticate
                            csrf_token_generator: security.csrf.token_manager
                            # submit the login form here
                            check_path: /login_check

                            # the user is redirected here when they need to log in
                            login_path: /login

                            # if true, forward the user to the login form instead of redirecting
                            use_forward: false

                            # login success redirecting options (read further below)
                            always_use_default_target_path: false
                            default_target_path:            /admin/produit
                            target_path_parameter:          _target_path
                            use_referer:                    false

            logout:
                path:   /logout
                target: /login
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_USER }