commande_index:
    path:     /
    defaults: { _controller: "AppBundle:Commande:index" }
    methods:  GET

commande_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Commande:show" }
    methods:  GET

commande_new:
    path:     /new
    defaults: { _controller: "AppBundle:Commande:new" }
    methods:  [GET, POST]

commande_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Commande:edit" }
    methods:  [GET, POST]

commande_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Commande:delete" }
    methods:  DELETE
commande_add:
    path:     /add
    defaults: { _controller: "AppBundle:Commande:add" }
    methods:  [GET, POST]
get_ville_by_code:
    path:     /getvillebyid
    defaults: { _controller: "AppBundle:Commande:getVilleById" }
    methods:  [GET, POST]