notification_index:
    path:     /
    defaults: { _controller: "AppBundle:Notification:index" }
    methods:  GET

notification_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Notification:show" }
    methods:  GET

notification_new:
    path:     /new
    defaults: { _controller: "AppBundle:Notification:new" }
    methods:  [GET, POST]

notification_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Notification:edit" }
    methods:  [GET, POST]

notification_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Notification:delete" }
    methods:  DELETE
